CXXFLAGS=-g -I ../Utils -I ../BeOS_UI -I ../Network -I. -I..

targets: DocElem.o DocElemStack.o DocWalker.o Event.o FormsDocElem.o Frame.o History.o Html.o MetaDocElem.o Pref.o Resource.o ResourceGetter.o StrDocElem.o Style.o Table.o Tag.o TagAttr.o TagDocElem.o TagDocElemFactory.o TextDocElem.o UrlQuery.o User.o VariousDocElem.o fwt.o
