#include "Tag.h"

/* This is the list of tags known by the browser. It doesn't mean that
   all tags listed here are supported but information provided here is
   usefull for parsing.
   XXX This list is incomplete.
*/

const TagInfo TagInfo::tagInfos[] = {
/*	NAME		DISPLAY		Margin		CLOSE MODE	REOPEN 
 *					TOP	BOTTOM
 */	{"/FONT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/STRONG",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/BIG",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/SMALL",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/EM",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{" BR",		D_BLOCK,	0,	-1,	NEVER_CLOSE,	true},
	{"/NOBR",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{" HR",		D_BLOCK,	2,	0,	NEVER_CLOSE,	true},
	{"/P",		D_BLOCK,	5,	0,	CAN_CLOSE,	false},
	{"/A",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/SPAN",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/TIME",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{" LINK",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{" META",	D_INLINE,	-1,	1,	NEVER_CLOSE,	true},
	{"/I",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/B",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/U",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/TT",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/LI",		D_BLOCK,	0,	-1,	ALWAYS_CLOSE,	false},
	{"/DD",		D_BLOCK,	0,	-1,	ALWAYS_CLOSE,	false},
	{"/DL",		D_BLOCK,	0,	-1,	ALWAYS_CLOSE,	false},
	{"/UL",		D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/OL",		D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/H1",		D_BLOCK,	6,	0,	ALWAYS_CLOSE,	false},
	{"/H2",		D_BLOCK,	5,	0,	ALWAYS_CLOSE,	false},
	{"/H3",		D_BLOCK,	4,	0,	ALWAYS_CLOSE,	false},
	{"/H4",		D_BLOCK,	2,	0,	ALWAYS_CLOSE,	false},
	{"/H5",		D_BLOCK,	1,	0,	ALWAYS_CLOSE,	false},
	{"/H6",		D_BLOCK,	0,	0,	ALWAYS_CLOSE,	false},
	{"/SUP",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false}, // Reopen ?
	{"/SUB",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false}, // Reopen ?
	{" IMG",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{"/STRIKE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/TD",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/TH",		D_BLOCK,	0,	0,	ALWAYS_CLOSE,	false},
	{"/TR",		D_BLOCK,	0,	0,	ALWAYS_CLOSE,	false},
	{"/TABLE",	D_BLOCK,	5,	5,	ALWAYS_CLOSE,	true},
	{"/HEADER",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/HGROUP",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/FOOTER",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/SECTION",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/ASIDE",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/ARTICLE",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/DIV",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/CENTER",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	true},
	{"/SCRIPT",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	false},	// due to a specific javascript parsing, this
									// tag is marked as NEVER_CLOSE
	{"/NOSCRIPT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{" FRAME",	D_BLOCK,	0,	-1,	NEVER_CLOSE,	false},
	{"/IFRAME",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/LAYER",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	false},
	{"/NOLAYER",	D_BLOCK,	0,	0,	ALWAYS_CLOSE,	false},
	{"/ILAYER",	D_INLINE,	0,	0,	ALWAYS_CLOSE,	true},
	{"/NOFRAMES",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/FRAMESET",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/INPUT",	D_INLINE,	-1,	-1,	CAN_CLOSE,	false},
	{"/LABEL",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{" TEXTAREA",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/BUTTON",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/SELECT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/OPTION",	D_INLINE,	-1,	-1,	CAN_CLOSE,	false},
	{"/FORM",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/PRE",	D_BLOCK,	0,	-1,	ALWAYS_CLOSE,	true},
	{" !--",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{"/BODY",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/TITLE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/HEAD",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{" BASE",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{" !DOCTYPE",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{"/HTML",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/STYLE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/INS",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true}, // INS and DEL are used for revision control
	{"/DEL",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true}, // 
	{"/FIELDSET",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/LEGEND",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/CAPTION",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/OBJECT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/COLGROUP",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{" COL",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/AREA",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/MAP",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/THEAD",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/TBODY",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/TFOOT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/CITE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/BLOCKQUOTE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/ADDRESS",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/CODE",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/ACRONYM",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/Q",		D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true}, // Small quotes
	{" SPACER",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	true},
	{"/SAMP",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/BASEFONT",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	true},
	{"/BLINK",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/KBD",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/DFN",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/DIR",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/LISTING",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/XMP",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},	// This one is deprecated. I don't think I should implement it
	{"/VAR",	D_INLINE,	-1,	-1,	ALWAYS_CLOSE,	false},
	{" WBR",	D_INLINE,	-1,	-1,	NEVER_CLOSE,	false},
	{"/MENU",	D_BLOCK,	1,	1,	ALWAYS_CLOSE,	false},
	{"/NAV",	D_BLOCK,	1,	1,	ALWAYS_CLOSE,	false},
	{"/EMBED",	D_BLOCK,	1,	1,	ALWAYS_CLOSE,	false},
	{" PARAM",	D_NONE,		1,	1,	NEVER_CLOSE,	false},
	{"/DT",		D_INLINE,	0,	-1,	ALWAYS_CLOSE,	false},
#ifdef __sun
	/* This is just experimentation for DocBook (man) format (SGML-based) */
	{"/PARA",	1,	1,	ALWAYS_CLOSE,	false},
	{"/REFENTRY",	1,	1,	ALWAYS_CLOSE,	false},
	{"/REFSECT1",	1,	1,	ALWAYS_CLOSE,	false},
	{"/SCREEN",	1,	1,	ALWAYS_CLOSE,	false},
	{"/COMPUTEROUTPUT",	1,	1,	ALWAYS_CLOSE,	false},
	{"/COMMAND",	-1,	-1,	ALWAYS_CLOSE,	false},
	{"/OLINK",	1,	1,	ALWAYS_CLOSE,	false},
	{"/CITEREFENTRY",	1,	1,	ALWAYS_CLOSE,	false},
	{"/MANVOLNUM",	1,	1,	ALWAYS_CLOSE,	false},
	{"/REFENTRYTITLE",	1,	1,	ALWAYS_CLOSE,	false},
	{"/INFORMALTABLE",	1,	1,	ALWAYS_CLOSE,	false},
	{"/TGROUP",	1,	1,	ALWAYS_CLOSE,	false},
	{"/ROW",	1,	1,	ALWAYS_CLOSE,	false},
	{"/ENTRY",	1,	1,	ALWAYS_CLOSE,	false},
	{"/VARIABLELIST",	1,	1,	ALWAYS_CLOSE,	false},
	{"/LISTITEM",	1,	1,	ALWAYS_CLOSE,	false},
	{"/VARLISTENTRY",	1,	1,	ALWAYS_CLOSE,	false},
	{"/TERM",	1,	1,	ALWAYS_CLOSE,	false},
	{"/FILENAME",	1,	1,	ALWAYS_CLOSE,	false},
	{"/RETURNVALUE",	1,	1,	ALWAYS_CLOSE,	false},
	{"/REPLACEABLE",	1,	1,	ALWAYS_CLOSE,	false},
#endif
	{NULL,		D_NONE,		0,	0,	NEVER_CLOSE,	false},
};
